<?php
use \Drupal\views\ViewExecutable;
use Drupal\Core\Routing\RouteMatchInterface;
use \Drupal\Core\Url;
use \Drupal\Core\Cache\Cache;
use Drupal\node\Entity\Node;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

  function hoya_world_map_page_attachments(array &$attachments) {
    $attachments['#attached']['library'][] = 'hoya_world_map/hoya_world_map_lib';
  }